[connections.gsheets]
type = "service_account"

project_id = "entry-form-431402"
private_key_id = "b52f91b113b46f9b94667c61184ecbc59a3c5e15"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCNa9NXSVCuDKQf
OuMujNOJWGlcaCvKFCcZ2PLgV6cCmXxSPN1RaT2C8k/TJRTd+Spit7l8ai6TlQVq
X3QPCZ92ok3SaR1OqgIXeGcBQdaiqSA6pfQhtPzIaz4DUTJ7jrRgR5cX7tYYB5FY
yXWZodPzU2sm1mkwIQ40KRbIK+s26XxNezePIOpsIFkfDl+iPcUM7xSg/EKeHTcH
C+Z1U9em4O1CkS0v6qqEJ3YmUwrOTDIfdr/9v/UlfICzcL0CcOxqRahTcqwO4+lW
rGRssUagNT9bp6rCuIuxey0QZ11/ga29GHBcEOdzqTnj06X2eugBrjxBE6H97w0Q
HTK8Nsq7AgMBAAECggEAGub/HiSpP2LSOcqm+uz5NLBn4pdCdT+eLJGTqk+iSqFO
AArqAxmlBOr5em4caRmEEaFnnJ5KW/LGQ/UCi/XFqvi3Gya514QJv9M8rQWMQgcw
RVfaeCsIx0t3UYQ5uT1tXL9ho8DgY1PVN3GjeGVLf4dH4+x3uBshq5SBa/TG2vwJ
HkA3AJkWFSFCvv4wueyQ4/6TQggTSGcTxHbn785Mhv5Of87nPgOtKZQ8anwWLC58
GkFNdN9WzJGXxYJ/4a87bk4jZwverd2QfynLOrp8Rchpl0BN+ivkFhsLnIiuAGbD
s6ekya8a8e+9JA725bjzCnDA9dnhviAW/z48LaxyuQKBgQDGz95xTKXE/nYLQwPH
bZVgT73lO0bECJoFh4li0vAA7StvhZQu+HVqsUJb6KJcIqcceigqib9rHEo37Yjz
6bts9NLvugwcFR85aOTE4WXzkakoTvpczzwD1ufl/VfwsBKThpnhm4XE+j99wXYa
atOilPvIE6ZW59fmPFkXqxAG9wKBgQC2Gc8uRPF9zZ1UPY9FmB6XnH36WFBWJHGX
kAFoSec696oAnvV/PBm0RKAwloLGXIiZB2k+PaG4DhNVDOg6sCA7esE6uIEeaAgy
Ppixyc5k78XdmglgDXHD9R+Suyr4kIBemozsJ8/ukBwdLt5ba3V7CAroLu3dyFSw
r+NUYT4VXQKBgQC7rDP2Tf1Z5T83SE6D7k0I+p1ui7M0kE4clCI7mJWYukm7X6RP
ZpkoWyYiLos9YDTR6/qIlTmN+cmR2/fhEC2uH7oTNFQEGmg8QGlb9M3RzBmbhFpQ
TAwCL9b+w1VFTmBqxK/0SWRQWk6e/oXnUBpxqiO3bd0iwn6Kx0Lu1bsuZwKBgF5I
hqiiMZa9OtQ++0tBM7Wz5NYVm6K+Q8IBYXkpqnsxd+fSZbF24KghT/9YLmWdy2vQ
FoGPT4gIYaILiMG6JzYknJ9WoCOqIXRCTLTgk+hW7M+LzYbZ7ylSZQKHvfvsdUqG
IqizBEm0e5nwhlg3DyCgTWVhxu6ppo/EwaMSph5RAoGAameic3tqtcmrJSL16WUw
KqWj4ISh8x5tDsE5VvoZbJw6Y47TtRq9wZ3KGT7k41tkiK8Ak9eAxkiyFyCHMwUr
HNXx5/Yr4cMu/+fV9aoWkUqbX15zIrAlyDJItqwxkvLOZciCQ8SAeLMFIKgMNG0i
iaJC0oZ1QgcQExFZE3qY9qc=
-----END PRIVATE KEY-----
"""

client_email = "gsheets-python-access@entry-form-431402.iam.gserviceaccount.com"
client_id = "111867060147919415922"

auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gsheets-python-access%40entry-form-431402.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
