[connections.gsheets]
type = "service_account"

project_id = "entry-form-431402"
private_key_id = "fffcaec52c1ee63f07948a13864f4106f4984c43"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDXqCd45YXyPX2P
HTtofTaIc2U7jbmq0G0r06DEjSv4EZ0kGjyApES3UGQvVb5LNJ6K1lOsUHxWP/io
oOnpb+Ypikx7kBm7ACbpKueHCY0VBXuT2Mh28BZBx/QjCTEDTv44vT2oTxD8VS03
1wd3myKK/XZUZJFynoINCVhBkRwWpMWAXORhvPCG6M/zNj6WoavOj5AEpNeUg8mv
Z0yg4uio5kSfzYJ5bzRyZdT6GDZP1ameY3Eg2Q/mYsCEKd6vlYyXoGe/d/MZiqTU
4TKeHeqSZF5iqOFP8ih6fG14LFasxQXDCYd9ys3emsEBTH4N4BpehR6ZenuZLxxH
A9LrVyj9AgMBAAECggEAZCqOavDwzhsRfq+tMFM4SRiQJKEnY9d7XafmPGT1zzsf
Ke2lvHqQEDUe032X7YZ7PTFfm+GmXslHzcsv2mVHGnRKIfpEeT8Q06xB7c7Z4LGz
PHCsa9IIBHXDR6K1STwfiGsdgFd5JDrLzevqY/uCh9xCYeB0TjChZzy36Xxk936m
REeCMd+ce8wF/+tR0glRbyOigtT6kEZcF7X+sAuyHdfgFcaO0zUILDI1gTYteD7L
blRMUETDHeHfg5Cn1jb46Uz3sTIIlrhbjVd11pdSPYK/xAsutUJTXGiIMn55RWe0
I6E5yFF0YdBIy43uzpJR2NvSnUhMdosqQfDpwtZSYQKBgQD4MMZJzzwH1drlylOm
2A8bkSSzTe0e9ELCe0TcNtWzYRVkcf3iFlILVBQQXqfh5Pp5OhosHuFeFpqsvErx
YU7PYoPol1i1dztdMFGcLLMa1wg4PKFJQrLUycgGok165Njn8B3O2mBrJqrK1P4p
IQ1iNVrMR68V2Ip/iwff99jHjwKBgQDecVBxllLEzYJtqKN4Nl8h5aROKRkHorxQ
wb28DagAQEOJvnlm+4mnmCStGQT2TlxnHU7mGsjoFZN8fWP6Xhjcjr74JDSNsNWN
KYxDo0unY/0a/YCberP8K3Uv6NrKQWvvcKWjKb8NLaNO0NDm860bPMNr4GdFMuMt
AboNBjJgswKBgDJUYcGR/tBv86Xps7D/24BxnImn4dAHJIqfyMUHcaqgo1/tJdj1
Qcn+UNtI9q5+arSuraQI1xbnapJg1KnCW+L+TVWba2fRN/6bz9Dl16Q3uvj8gpCC
sBUqnh+KRkAHrFzMep759deEzdm3+5qHk1k5DKKkXsMFWICoxv4KGrHNAoGAIUzP
YSHC5ElrtCThy/Y/yaBKN5U5dQYssN5AHC3jL55vPeiw3fTcB6XkH7G2J3VVqe4e
SJ5L40qPmLxgwjNh/2qzNgydfXSyk35bzChfBAEY+/hlT2FQHnkXAwQV9N9UXDT9
5u4x9rQVVZA3Jcvm50PycWzXqOlUTwGKK7b4xbcCgYEA12MjMBOhQLQsBhKPN+Qq
vz6LAi/uj7JNCtI6OkZu2CLuKlW2SSj/5JXJ4XPiPtXZz5rQ0uqjr5TeudbtQJKk
Ivh7XEjWGBYQWjWTKnoZjSULPT80U3OK0eHJbCA6bkkDJbPod517RLrUlNt8OJUk
79CWOtn4GdIIkxH50Dl06vM=
-----END PRIVATE KEY-----"""

client_email = "gsheets-python-access@entry-form-431402.iam.gserviceaccount.com"
client_id = "111867060147919415922"

auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/gsheets-python-access%40entry-form-431402.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
